changeLogFile=changelog/changelog-master.xml
url=jdbc:postgresql://localhost:1212/myDB
username=admin
password=masterkey
defaultSchemaName=public
driver=org.postgresql.Driver
classpath=lib/postgresql-42.7.3.jar
logLevel=info
liquibase.hub.mode=off
