--liquibase formatted sql

--changeset lab6:002-create-product-media
CREATE TABLE product_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    url VARCHAR NOT NULL,
    alt_text VARCHAR,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_media_product_fk FOREIGN KEY (product_id) REFERENCES products (id)
);
--rollback DROP TABLE IF EXISTS product_media;

--changeset lab6:002-create-product-media-indexes
CREATE INDEX product_media_product_idx ON product_media (product_id);
CREATE UNIQUE INDEX product_media_primary_unique ON product_media (product_id) WHERE is_primary;
--rollback DROP INDEX IF EXISTS product_media_primary_unique; DROP INDEX IF EXISTS product_media_product_idx;
